//containing name:sellprice pairs
let priceData = {
    "Small trout": "5",
    "Roasted small trout": "100",
    "Bronze bar": "400",
    "Cobweb": "1",
    "Manure": "1",
    "Twig": "1",
    "Scrap": "1",
    "Fishing rod": "30",
    "Tinder": "5",
    "Flint": "5",
    "Wooden stick": "10",
    "Thread": "2",
    "Fishing hook": "2",
    "Potato seed": "1",
    "Potato": "5",
    "Chisel": "30",
    "Weak bow": "20",
    "Emerald": "7000",
    "Flint spear": "100",
    "Sharp flint": "5",
    "Uncut emerald": "1000",
    "Tomato seed": "1",
    "Chalk": "1",
    "Flint spearhead": "50",
    "Copper ore": "12",
    "Torch": "10",
    "Old gloves": "10",
    "Old pickaxe": "60",
    "Flint hatchet": "25",
    "Flint arrowhead": "8",
    "Carrot": "5",
    "Small spotted bass": "10",
    "Oak log": "8",
    "Tomato": "8",
    "Carrot seed": "1",
    "Roasted small spotted bass": "40",
    "Arrow shaft": "4",
    "Old boot": "70",
    "Sapphire": "4000",
    "Uncut sapphire": "500",
    "Tin ore": "15",
    "Bronze hammerhead": "5",
    "Bronze hammer": "125",
    "Iron ore": "20",
    "Small carp": "6",
    "Uncut opal": "2000",
    "Small salmon": "8",
    "Small catfish": "7",
    "Roasted small carp": "80",
    "Empty bottle": "30",
    "Roasted small salmon": "160",
    "Roasted small catfish": "140",
    "Uncut ruby": "1500",
    "Strong fishing rod": "50",
    "Salmon": "15",
    "Catfish": "17",
    "Guadalupe bass": "19",
    "Spotted bass": "20",
    "Carp": "12",
    "Trout": "15",
    "Roasted guadalupe bass": "40",
    "Roasted trout": "200",
    "Roasted spotted bass": "90",
    "Roasted salmon": "350",
    "Small guadalupe bass": "9",
    "Roasted carp": "250",
    "Roasted catfish": "300",
    "Log": "5",
    "Roasted small guadalupe bass": "40"
}

//add time as a resource
priceData["time"] = 0;