//containing name:sellprice pairs

let priceData = {
    "small trout": "5",
    "roasted small trout": "100",
    "bronze bar": "400",
    "cobweb": "1",
    "manure": "1",
    "twig": "1",
    "scrap": "1",
    "fishing rod": "30",
    "tinder": "5",
    "flint": "5",
    "wooden stick": "10",
    "thread": "2",
    "fishing hook": "2",
    "potato seed": "1",
    "potato": "5",
    "chisel": "30",
    "weak bow": "20",
    "emerald": "7000",
    "flint spear": "100",
    "sharp flint": "5",
    "uncut emerald": "1000",
    "tomato seed": "1",
    "chalk": "1",
    "flint spearhead": "50",
    "copper ore": "12",
    "torch": "10",
    "old gloves": "10",
    "old pickaxe": "60",
    "flint hatchet": "25",
    "flint arrowhead": "8",
    "carrot": "5",
    "small spotted bass": "10",
    "oak log": "8",
    "spruce log": "25",
    "tomato": "8",
    "carrot seed": "1",
    "roasted small spotted bass": "40",
    "arrow shaft": "4",
    "old boot": "70",
    "sapphire": "4000",
    "uncut sapphire": "500",
    "tin ore": "15",
    "bronze hammerhead": "5",
    "bronze hammer": "125",
    "iron ore": "20",
    "silver ore": "25",
    "small carp": "6",
    "uncut opal": "2000",
    "small salmon": "8",
    "small catfish": "7",
    "roasted small carp": "80",
    "empty bottle": "30",
    "roasted small salmon": "160",
    "roasted small catfish": "140",
    "uncut ruby": "1500",
    "strong fishing rod": "50",
    "salmon": "15",
    "catfish": "17",
    "guadalupe bass": "19",
    "spotted bass": "20",
    "carp": "12",
    "trout": "15",
    "roasted guadalupe bass": "40",
    "roasted trout": "200",
    "roasted spotted bass": "90",
    "roasted salmon": "350",
    "small guadalupe bass": "9",
    "roasted carp": "250",
    "roasted catfish": "300",
    "log": "5",
    "roasted small guadalupe bass": "40",
    "opal": "17000",
    "ruby": "13000"
}